language: node_js
node_js:
  - 'stable'
cache:
  yarn: true
  directories:
    - node_modules
    - website/node_modules
branches:
  only:
    - master
    - next
    - patch
install:
  - yarn
script:
  - yarn lint
