name: 'Feature Request'
description: 'Request a feature or enhancement'
labels: ['v3', 'feature request', 'triage']
body:
  - type: 'markdown'
    attributes:
      value: |
        Thanks for filing an issue!

        Please search open/closed issues before submitting. Someone might have asked the same thing before!

        ### Help us help you better
  - type: 'textarea'
    id: 'description'
    attributes:
      label: 'Description'
      description: 'Describe your request as clearly as possible.'
      placeholder: "We'll love to know in depth about this feature"
    validations:
      required: true
  - type: 'textarea'
    id: 'justification'
    attributes:
      label: 'Problem Statement'
      description: |
        Please provide valid reason(s) why this should be a part of NativeBase

        Does this feature meant to solve an existing problem, if so please mention it as well.
      placeholder: 'Tell us What? Why? and How?'
    validations:
      required: true
  - type: 'textarea'
    id: 'proposed-solution'
    attributes:
      label: 'Proposed Solution or API'
      description: |
        Please provide code snippets, gists, or links to the ideal design or API.
      placeholder: "We know whatever you're it is, its awesome"
    validations:
      required: true
  - type: 'textarea'
    id: 'alternatives'
    attributes:
      label: 'Alternatives'
      description: |
        What alternative solutions have you considered before making this request?
      placeholder: 'Please share if you know any alternative solutions as well'
  - type: 'textarea'
    id: 'additional-information'
    attributes:
      label: 'Additional Information'
      description: |
        What resources (links, screenshots, etc.) do you have to assist this effort?
      placeholder: 'Any and every additional information is always welcome'
